apiVersion: apps/v1
kind: Deployment
metadata:
  name: myusage-api-deployment
  labels:
    app: myusage-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myusage-api
  template:
    metadata:
      labels:
        app: myusage-api
    spec:
      containers:
      - name: myusage-api
        imagePullPolicy: Always
        image: charltruter/myusage-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: myusage-secrets
              key: db_username
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: myusage-secrets
              key: db_password
        - name: MYSQL_DB
          valueFrom:
            secretKeyRef:
              name: myusage-secrets
              key: db_name
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: myusage-secrets
              key: db_host
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: myusage-secrets
              key: jwt_secret
        - name: NODE_ENV
          value: "production"
      imagePullSecrets:
        - name: myregistrykey
